import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { Client } from "@modelcontextprotocol/client";
import { InMemoryTransport, McpServer } from "@modelcontextprotocol/server";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { AGENT_GUIDE, EXAMPLES, GRAMMAR, GRAMMAR_FULL, POSTS_FORMAT } from "../src/content/index.js";
import type { ToolContext } from "../src/context.js";
import { LIST_CACHE_HINTS, registerReference } from "../src/reference.js";
import { TOPICS, runGetMarkupReference } from "../src/reference/tool.js";
import { DOCS, EXAMPLE_NAMES, examplesIndex } from "../src/reference/topics.js";

const CONTENT_DIR = join(import.meta.dirname, "..", "src", "content");
const stripHeader = (s: string): string => s.replace(/^<!-- Generated by [^\n]*-->\n\n/, "");

const textOf = (result: { content: Array<{ type: string; text?: string }> }): string =>
  result.content.map((c) => (c.type === "text" ? c.text : "")).join("");

describe("content index", () => {
  it("embeds every example file, each a non-empty .page with a [site] block and a page", () => {
    const files = readdirSync(join(CONTENT_DIR, "examples")).filter((f) => f.endsWith(".page"));
    expect(files.length).toBeGreaterThanOrEqual(11);
    expect(Object.keys(EXAMPLES).sort()).toEqual(files.map((f) => f.replace(/\.page$/, "")).sort());
    for (const [name, body] of Object.entries(EXAMPLES)) {
      expect(body.trim().length, name).toBeGreaterThan(0);
      expect(body, name).toMatch(/^\[site\]$/m);
      expect(body, name).toMatch(/^\[[^\]]+ -> \/[^\]]*\]$/m);
      expect(body, name).toBe(readFileSync(join(CONTENT_DIR, "examples", `${name}.page`), "utf8"));
    }
  });

  it.each([
    ["grammar.md", GRAMMAR],
    ["grammar-full.md", GRAMMAR_FULL],
    ["agent-guide.md", AGENT_GUIDE],
    ["posts-format.md", POSTS_FORMAT],
  ])("%s is generated, non-empty and identical to the embedded string", (file, embedded) => {
    const onDisk = readFileSync(join(CONTENT_DIR, file), "utf8");
    expect(onDisk.startsWith("<!-- Generated by scripts/sync-content.mjs")).toBe(true);
    expect(embedded.trim().length).toBeGreaterThan(200);
    expect(stripHeader(onDisk)).toBe(embedded);
  });

  it("posts format covers the fields upsert_post takes and the re-send warning", () => {
    for (const field of ["title", "slug", "description", "visibility", "hero", "list", "subject", "preview"]) {
      expect(POSTS_FORMAT).toContain(`\`${field}\``);
    }
    expect(POSTS_FORMAT).toMatch(/re-sends the email/);
  });

  it("the example index names every example", () => {
    const index = examplesIndex();
    for (const name of EXAMPLE_NAMES) expect(index).toContain(`\`${name}\``);
  });
});

describe("over MCP", () => {
  let client: Client;
  let server: McpServer;

  beforeAll(async () => {
    server = new McpServer({ name: "micropage-test", version: "0.0.0" }, { cacheHints: LIST_CACHE_HINTS });
    registerReference(server, {} as ToolContext);
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    await server.connect(serverTransport);
    client = new Client({ name: "test", version: "0.0.0" });
    await client.connect(clientTransport);
  });

  afterAll(async () => {
    await client.close();
    await server.close();
  });

  it("lists every static resource and every example", async () => {
    const { resources } = await client.listResources();
    const uris = resources.map((r) => r.uri);
    for (const doc of DOCS) expect(uris).toContain(doc.uri);
    for (const name of EXAMPLE_NAMES) expect(uris).toContain(`micropage://examples/${name}`);
    for (const r of resources) expect((r.description ?? "").length, r.uri).toBeGreaterThan(120);
  });

  it("advertises the example template", async () => {
    const { resourceTemplates } = await client.listResourceTemplates();
    const t = resourceTemplates.find((r) => r.uriTemplate === "micropage://examples/{name}");
    expect(t).toBeDefined();
    expect((t?.description ?? "").length).toBeGreaterThan(120);
  });

  it("resolves every listed resource URI to its text", async () => {
    const { resources } = await client.listResources();
    for (const r of resources) {
      const { contents } = await client.readResource({ uri: r.uri });
      const first = contents[0] as { uri: string; text?: string } | undefined;
      expect(first?.uri, r.uri).toBe(r.uri);
      expect((first?.text ?? "").length, r.uri).toBeGreaterThan(0);
    }
    const grammar = await client.readResource({ uri: "micropage://grammar" });
    expect((grammar.contents[0] as { text: string }).text).toBe(GRAMMAR);
    const ex = await client.readResource({ uri: "micropage://examples/startup-landing" });
    expect((ex.contents[0] as { text: string }).text).toBe(EXAMPLES["startup-landing"]);
  });

  it("rejects an unknown example URI", async () => {
    await expect(client.readResource({ uri: "micropage://examples/nope" })).rejects.toThrow();
  });

  it("completes example names", async () => {
    const res = await client.complete({
      ref: { type: "ref/resource", uri: "micropage://examples/{name}" },
      argument: { name: "name", value: "components-" },
    });
    expect(res.completion.values.length).toBeGreaterThanOrEqual(3);
    for (const v of res.completion.values) expect(v.startsWith("components-")).toBe(true);
  });

  const PROMPT_ARGS: Record<string, Record<string, string>> = {
    create_landing_page: { brief: "A waitlist for a habit-tracking app" },
    edit_page: { project: "acme.micropage.sh", change: "Make the hero headline shorter" },
    write_post: { project: "acme.micropage.sh", topic: "Our spring release" },
    review_submissions: { project: "acme.micropage.sh" },
  };

  it("lists exactly the four prompts, each with a long description", async () => {
    const { prompts } = await client.listPrompts();
    expect(prompts.map((p) => p.name).sort()).toEqual(Object.keys(PROMPT_ARGS).sort());
    for (const p of prompts) expect((p.description ?? "").length, p.name).toBeGreaterThan(120);
  });

  it.each(Object.entries(PROMPT_ARGS))("renders %s with only its required args", async (name, args) => {
    const res = await client.getPrompt({ name, arguments: args });
    const text = res.messages.map((m) => (m.content.type === "text" ? m.content.text : "")).join("\n");
    for (const value of Object.values(args)) expect(text).toContain(value);
    expect(text).not.toMatch(/undefined|\[object Object\]/);
  });

  it("names the tools other units implement, and the safety rules", async () => {
    const render = async (name: string, args: Record<string, string>): Promise<string> => {
      const res = await client.getPrompt({ name, arguments: args });
      return res.messages.map((m) => (m.content.type === "text" ? m.content.text : "")).join("\n");
    };
    const create = await render("create_landing_page", { ...PROMPT_ARGS.create_landing_page!, style: "minimal" });
    expect(create).toContain("save_page");
    expect(create).toContain("publish_build");
    expect(create).toContain("minimal");
    expect(create).toMatch(/explicitly ask/);

    const edit = await render("edit_page", PROMPT_ARGS.edit_page!);
    expect(edit.indexOf("get_page_source")).toBeLessThan(edit.indexOf("save_page"));

    const post = await render("write_post", { ...PROMPT_ARGS.write_post!, audience: "existing customers" });
    for (const tool of ["upsert_post", "preview_post_send", "publish_post", "MICROPAGE_MCP_ALLOW_SEND"]) {
      expect(post).toContain(tool);
    }
    expect(post).toContain("existing customers");

    const review = await render("review_submissions", { project: "acme.micropage.sh", form: "waitlist" });
    expect(review).toContain("list_submissions");
    expect(review).toContain('"waitlist"');
    expect(review).toMatch(/untrusted|strictly as data/);
  });

  it("registers get_markup_reference as local read-only with a long description", async () => {
    const { tools } = await client.listTools();
    const tool = tools.find((t) => t.name === "get_markup_reference");
    expect(tool).toBeDefined();
    expect((tool?.description ?? "").length).toBeGreaterThan(120);
    expect(tool?.annotations).toMatchObject({
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    });
  });

  it("serves an example through the tool over the wire", async () => {
    const res = await client.callTool({
      name: "get_markup_reference",
      arguments: { topic: "example", example: "portfolio" },
    });
    expect(textOf(res as never)).toBe(EXAMPLES.portfolio);
  });
});

describe("get_markup_reference", () => {
  it.each(TOPICS.filter((t) => t !== "example"))("returns the text for topic %s", (topic) => {
    const res = runGetMarkupReference({ topic });
    expect(res.isError).toBeUndefined();
    const doc = DOCS.find((d) => d.topic === topic);
    expect(textOf(res)).toBe(doc?.text());
  });

  it("defaults to the grammar", () => {
    expect(textOf(runGetMarkupReference({}))).toBe(GRAMMAR);
  });

  it.each(EXAMPLE_NAMES)("returns example %s", (name) => {
    expect(textOf(runGetMarkupReference({ topic: "example", example: name }))).toBe(EXAMPLES[name]);
  });

  it("infers the example topic and tolerates a .page suffix", () => {
    expect(textOf(runGetMarkupReference({ example: "portfolio.page" }))).toBe(EXAMPLES.portfolio);
  });

  it("an unknown example is an error that lists every valid name", () => {
    const res = runGetMarkupReference({ topic: "example", example: "wedding" });
    expect(res.isError).toBe(true);
    const text = textOf(res);
    expect(text).toContain('"wedding"');
    for (const name of EXAMPLE_NAMES) expect(text).toContain(name);
  });

  it("topic example without a name is an error that lists every valid name", () => {
    const res = runGetMarkupReference({ topic: "example" });
    expect(res.isError).toBe(true);
    for (const name of EXAMPLE_NAMES) expect(textOf(res)).toContain(name);
  });
});
