#!/usr/bin/env node
/**
 * Copies the markup reference from its sources in the monorepo into
 * src/content/ (generated, committed), then writes src/content/index.ts so
 * the server embeds the text and never reads the filesystem at runtime.
 *
 *   npm run sync-content
 *
 * Sources of truth (edit those, not the copies):
 *   ../docs/static/llms.txt, ../docs/static/llms-full.txt
 *   ../cli/templates/PROJECT_AGENT.template.md
 *   ../docs/docs/cli/posts.md, ../docs/docs/concepts/posts.md
 *   ../cli/templates/examples/*.page
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const MCP_DIR = join(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = join(MCP_DIR, "..");
const OUT = join(MCP_DIR, "src", "content");

const src = (...p) => join(ROOT, ...p);
const rel = (p) => relative(ROOT, p);

function read(path) {
  if (!existsSync(path)) {
    console.error(`sync-content: missing source ${rel(path)}. Run this from a full monorepo checkout.`);
    process.exit(1);
  }
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

/**
 * The body of a `## heading` section, up to the next heading of the same or
 * higher level. Fence-aware, because YAML front-matter examples inside code
 * blocks contain lines that look like markdown.
 */
function section(md, heading, { level = 2 } = {}) {
  const lines = md.split("\n");
  const prefix = "#".repeat(level) + " ";
  const start = lines.findIndex((l) => l.trim() === prefix + heading);
  if (start === -1) throw new Error(`sync-content: section "${prefix}${heading}" not found`);
  let inFence = false;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (/^\s*```/.test(lines[i])) inFence = !inFence;
    if (inFence) continue;
    const m = /^(#{1,6}) /.exec(lines[i]);
    if (m && m[1].length <= level) {
      end = i;
      break;
    }
  }
  return lines.slice(start + 1, end).join("\n").trim();
}

const tidy = (s) => s.replace(/\n{3,}/g, "\n\n").trim() + "\n";

const header = (sources) =>
  `<!-- Generated by scripts/sync-content.mjs from ${sources.join(", ")}. ` +
  `Do not edit: change the source and run npm run sync-content. -->\n\n`;

// --- grammar ---------------------------------------------------------------

const grammar = read(src("docs/static/llms.txt"));
const grammarFull = read(src("docs/static/llms-full.txt"));

// --- agent guide -----------------------------------------------------------

const templatePath = src("cli/templates/PROJECT_AGENT.template.md");
const template = read(templatePath);
// The tone placeholder is for a human to fill in a scaffolded project; it
// means nothing to an agent reading the guide over MCP.
const agentGuide = tidy(template.replace(/^<!-- PROJECT_TONE:.*-->\s*$/m, ""));

// --- posts format ----------------------------------------------------------

const cliPostsPath = src("docs/docs/cli/posts.md");
const conceptsPostsPath = src("docs/docs/concepts/posts.md");

// The template's Posts section, minus its CLI command list: over MCP the
// tools replace those commands.
const templatePosts = section(template, "Posts").split(/\n\s*Commands:\s*\n/)[0].trim();
const fieldTable = section(read(cliPostsPath), "Post files")
  .split("\n")
  .filter((l) => l.startsWith("|"))
  .join("\n");
// "(see below)" points at a click-tracking section this excerpt leaves out.
const lifecycle = section(read(conceptsPostsPath), "Lifecycle").replace(/ \(see below\)/g, "");

const postsFormat = tidy(
  [
    "# Posts format",
    "",
    "Over MCP a post is written with the `upsert_post` tool: the front-matter fields below are its arguments and `body_markdown` is the Markdown body. The file form below is what the CLI uses for `posts/*.md`.",
    "",
    "## Post file",
    "",
    templatePosts,
    "",
    "## Fields",
    "",
    fieldTable,
    "",
    "## Lifecycle",
    "",
    lifecycle,
  ].join("\n"),
);

// --- examples --------------------------------------------------------------

const examplesDir = src("cli/templates/examples");
const exampleFiles = readdirSync(examplesDir)
  .filter((f) => f.endsWith(".page"))
  .sort();
if (exampleFiles.length === 0) throw new Error(`sync-content: no .page files in ${rel(examplesDir)}`);
const examples = Object.fromEntries(
  exampleFiles.map((f) => [f.replace(/\.page$/, ""), read(join(examplesDir, f))]),
);

// --- write -----------------------------------------------------------------

mkdirSync(OUT, { recursive: true });
rmSync(join(OUT, "examples"), { recursive: true, force: true });
mkdirSync(join(OUT, "examples"));

const docs = [
  ["grammar.md", grammar, ["docs/static/llms.txt"]],
  ["grammar-full.md", grammarFull, ["docs/static/llms-full.txt"]],
  ["agent-guide.md", agentGuide, [rel(templatePath)]],
  ["posts-format.md", postsFormat, [rel(templatePath), rel(cliPostsPath), rel(conceptsPostsPath)]],
];
for (const [name, body, sources] of docs) writeFileSync(join(OUT, name), header(sources) + body);

// .page has no comment syntax, so the examples are byte-for-byte copies; the
// generated marker for them lives in index.ts.
for (const f of exampleFiles) writeFileSync(join(OUT, "examples", f), read(join(examplesDir, f)));

const lit = (s) => JSON.stringify(s);
const exampleEntries = Object.entries(examples)
  .map(([name, body]) => `  ${lit(name)}: ${lit(body)},`)
  .join("\n");

const index = `// Generated by scripts/sync-content.mjs. Do not edit: change the sources and run
// npm run sync-content. Embedded as strings so the server reads no files at
// runtime (and stays usable from a remote, filesystem-less deployment).
//
// Sources (monorepo-relative):
//   GRAMMAR       docs/static/llms.txt
//   GRAMMAR_FULL  docs/static/llms-full.txt
//   AGENT_GUIDE   ${rel(templatePath)}
//   POSTS_FORMAT  ${rel(templatePath)} (Posts), ${rel(cliPostsPath)} (Post files), ${rel(conceptsPostsPath)} (Lifecycle)
//   EXAMPLES      ${rel(examplesDir)}/*.page

export const GRAMMAR: string = ${lit(grammar)};

export const GRAMMAR_FULL: string = ${lit(grammarFull)};

export const AGENT_GUIDE: string = ${lit(agentGuide)};

export const POSTS_FORMAT: string = ${lit(postsFormat)};

export const EXAMPLES: Readonly<Record<string, string>> = Object.freeze({
${exampleEntries}
});
`;
writeFileSync(join(OUT, "index.ts"), index);

console.log(
  `sync-content: wrote ${docs.length} documents and ${exampleFiles.length} examples to ${relative(MCP_DIR, OUT)}/`,
);
